

services:
  postgres:
    image: postgres:16.3
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: notes
      POSTGRES_PASSWORD: "k_f0TmVTOoQHYpeTBvVP918dZJkz4ppj"
    volumes:
      - notes_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "VT2wXnBN39ZSilFqMuVIgfi0CDJDRkya"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  notes_data:
